#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:
  ex-market-data-service-sandbox:
    image: digitalasset/ex-market-data-service-sandbox:0.0.1
    build:
      context: .
      dockerfile: Dockerfile-sandbox
    ports:
      - "127.0.0.1:6865:6865"

  ex-market-data-service-triggers:
    image: digitalasset/ex-market-data-service-triggers:0.0.1
    build:
      context: .
      dockerfile: Dockerfile-triggers
    depends_on:
      - "ex-market-data-service-sandbox"
    environment:
      - SANDBOX_HOST=ex-market-data-service-sandbox
      - SANDBOX_PORT=6865

  ex-market-data-service-bots:
    image: digitalasset/ex-market-data-service-bots:0.0.1
    build:
      context: .
      dockerfile: Dockerfile-bots
    depends_on:
      - "ex-market-data-service-triggers"
    volumes:
      - ./data:/home/sdk/data
    environment:
      - SANDBOX_HOST=ex-market-data-service-sandbox
      - SANDBOX_PORT=6865

  ex-market-data-service-navigator:
    image: digitalasset/ex-market-data-service-navigator:0.0.1
    build:
      context: .
      dockerfile: Dockerfile-navigator
    depends_on:
      - "ex-market-data-service-sandbox"
    ports:
      - "127.0.0.1:7500:7500"
    environment:
      - SANDBOX_HOST=ex-market-data-service-sandbox
      - SANDBOX_PORT=6865
