#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
#

ARG sdk_vsn=1.5.0

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/daml

COPY --chown=daml target/market-data-service.dar /home/daml/

USER daml

EXPOSE 6865

CMD ~/.daml/bin/daml sandbox -- --wall-clock-time --address 0.0.0.0 --port 6865 market-data-service.dar --ledgerid market-data-service
