#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
#

ARG sdk_vsn=0.13.51

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/daml

COPY --chown=daml ui-backend.conf frontend-config.js /home/daml/

USER daml

EXPOSE 7500

# DAML-on-X version
# CMD ~/.daml/bin/daml ledger navigator --host ${SANDBOX_HOST} --port ${SANDBOX_PORT} -- --port 7500

# Demo version
CMD ~/.daml/bin/daml navigator -- server ${SANDBOX_HOST} ${SANDBOX_PORT} --port 7500 --config-file ui-backend.conf

