#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
#

ARG sdk_vsn=1.1.1

FROM digitalasset/daml-sdk:${sdk_vsn} AS source

WORKDIR /home/daml/

USER daml
COPY --chown=daml daml.yaml ./
COPY --chown=daml src/main/daml src/main/daml
COPY --chown=daml ui-backend.conf frontend-config.js /home/daml/

EXPOSE 6865

ENTRYPOINT daml start \
  --sandbox-option="--address=0.0.0.0" \
  --sandbox-option="--static-time" \
  --sandbox-port=6865 \
  --start-navigator=false \
  --json-api-port=none
