#!/usr/bin/env bash
#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

exec java -jar target/market-data-service-0.0.1-SNAPSHOT.jar -ledgerId market-data-service
