#!/usr/bin/env bash
#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -e

if [ $# -lt 1 ]
then
  SANDBOX_PORT=6865
else
  SANDBOX_PORT="${1}"
fi

scripts/populate.py "$SANDBOX_PORT"
echo "DAML script executed"

scripts/startTriggers.py "$SANDBOX_PORT"
