#!/usr/bin/env bash
#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

exec daml start --start-navigator true \
  --sandbox-option --address=localhost \
  --sandbox-option --wall-clock-time \
  --sandbox-option --ledgerid=market-data-service
